name: Deploy to Goggle App Engine (GAE)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Archive production artifacts
      run: tar -czf nextjs-app.tar.gz .next public package.json next.config.js

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nextjs-app
        path: nextjs-app.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: nextjs-app
        path: .

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Decompress artifact
      run: tar -xzf nextjs-app.tar.gz

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet